using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Sapling.Shared.Content;
using Sapling.Web.Data;

namespace Sapling.Web.Services;

public sealed record CareerSource(
    string Name, string Publisher, string Url, string License, string LicenseUrl, string OutlookSource, string Modifications, string ImportedOn);

public sealed record CatalogueRequirement(
    string Skill, string Kind, int Impact, int Effort, int Weeks, string Rationale, string? Category);

public sealed record CatalogueCheckpoint(string Title, int Lessons, int Minutes);

public sealed record CatalogueCourse(
    string Id, string Provider, string Title, string Byline, string Url, int Lessons, int Minutes, CatalogueCheckpoint[] Checkpoints);

public sealed record CatalogueSkillCourse(string Course, string Match);

public sealed record CatalogueRole(
    string Onet,
    string Title,
    string OnetTitle,
    string Family,
    string Description,
    string[] Tasks,
    string[] AlsoCalled,
    string[] Technologies,
    int JobZone,
    string[] Outlook,
    string Preparation,
    string Education,
    Dictionary<string, double> Interests,
    string[] Related,
    string[] Core,
    string[] Adjacent,
    string[] Primary,
    CatalogueRequirement[] Requirements);

/// <summary>Data/careers.json, generated by tools/careers/import.cs from O*NET plus Sapling's course mapping.</summary>
public sealed record CareerCatalogueFile(
    CareerSource Source,
    string CourseMapping,
    Dictionary<string, string[]> KnowledgeEvidence,
    Dictionary<string, int[]> EffortByCategory,
    string[] VagueKnowledge,
    Dictionary<string, string[]> CourseBasics,
    string[] EverydaySkills,
    string LearningSource,
    CatalogueCourse[] LearningCourses,
    Dictionary<string, CatalogueSkillCourse[]> SkillCourses,
    CatalogueRole[] Roles)
{
    public const string Primary = "Primary";
    public const string Core = "Core";
    public const string Adjacent = "Adjacent";

    public static CareerCatalogueFile Load()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Data", "careers.json");
        return JsonSerializer.Deserialize<CareerCatalogueFile>(
                   File.ReadAllText(path), new JsonSerializerOptions(JsonSerializerDefaults.Web))
               ?? throw new InvalidOperationException($"{path} is empty.");
    }

    /// <summary>
    /// Makes the database match the file: roles are matched on their O*NET code, their requirements and course
    /// links are rewritten, and roles no longer in the file are removed after students aiming at them are moved.
    /// </summary>
    public async Task SyncAsync(SaplingDbContext db, ILogger logger)
    {
        await using var transaction = await db.Database.BeginTransactionAsync();

        var skills = await db.Skills.ToDictionaryAsync(s => s.Name, StringComparer.OrdinalIgnoreCase);
        foreach (var requirement in Roles.SelectMany(r => r.Requirements).DistinctBy(r => r.Skill, StringComparer.OrdinalIgnoreCase))
        {
            if (!skills.ContainsKey(requirement.Skill))
            {
                var skill = new Skill { Name = requirement.Skill, Category = requirement.Category ?? "Other" };
                db.Skills.Add(skill);
                skills[skill.Name] = skill;
            }
        }

        var roles = await db.CareerRoles.ToListAsync();
        var byCode = roles.Where(r => r.OnetCode != "").ToDictionary(r => r.OnetCode);
        foreach (var source in Roles)
        {
            if (!byCode.TryGetValue(source.Onet, out var role))
            {
                role = new CareerRole { OnetCode = source.Onet };
                db.CareerRoles.Add(role);
                byCode[source.Onet] = role;
            }

            role.Title = source.Title;
            role.OnetTitle = source.OnetTitle;
            role.Family = source.Family;
            role.Description = source.Description;
            role.Tasks = Join(source.Tasks);
            role.AlsoCalled = Join(source.AlsoCalled);
            role.Technologies = Join(source.Technologies);
            role.JobZone = source.JobZone;
            role.Outlook = Join(source.Outlook);
            role.Preparation = source.Preparation;
            role.Education = source.Education;
            role.Interests = Join(source.Interests.Select(p => $"{p.Key}:{p.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}"));
            role.RelatedCodes = Join(source.Related);
        }

        await db.SaveChangesAsync();

        var ids = Roles.Select(r => byCode[r.Onet].Id).ToList();
        await db.RoleSkillRequirements.Where(r => ids.Contains(r.CareerRoleId)).ExecuteDeleteAsync();
        await db.CourseRoleLinks.Where(l => ids.Contains(l.CareerRoleId)).ExecuteDeleteAsync();

        foreach (var source in Roles)
        {
            var roleId = byCode[source.Onet].Id;
            db.RoleSkillRequirements.AddRange(source.Requirements.Select(r =>
            {
                var skill = skills[r.Skill];

                // The effort estimate follows the skill's category as the app knows it.
                var (effort, weeks) = EffortByCategory.TryGetValue(skill.Category, out var e) && e.Length == 2 ? (e[0], e[1]) : (r.Effort, r.Weeks);
                return new RoleSkillRequirement
                {
                    CareerRoleId = roleId,
                    SkillId = skill.Id,
                    Kind = r.Kind,
                    Impact = r.Impact,
                    Effort = effort,
                    WeeksToClose = weeks,
                    Rationale = r.Rationale,
                };
            }));

            db.CourseRoleLinks.AddRange(Links(source).Select(l => new CourseRoleLink
            {
                CareerRoleId = roleId,
                Course = l.Course,
                Branch = l.Branch,
                Relevance = l.Relevance,
            }));
        }

        await db.SaveChangesAsync();

        var current = ids.ToHashSet();
        var profiles = await db.StudentProfiles.Where(p => !current.Contains(p.TargetRoleId)).ToListAsync();
        foreach (var profile in profiles)
        {
            profile.TargetRoleId = byCode[DefaultRoleFor(profile.Branch).Onet].Id;
        }

        await db.SaveChangesAsync();

        var removed = await db.CareerRoles.Where(r => !current.Contains(r.Id)).ExecuteDeleteAsync();
        await SyncCoursesAsync(db, skills);
        await transaction.CommitAsync();

        if (removed > 0 || profiles.Count > 0)
        {
            logger.LogInformation("Career catalogue: removed {Removed} old roles and moved {Moved} students to a role for their course", removed, profiles.Count);
        }
    }

    /// <summary>
    /// Courses are matched on their provider id and checkpoints on their position, so a re-import keeps every
    /// student's ticks. Only checkpoints beyond a course's new length are removed.
    /// </summary>
    private async Task SyncCoursesAsync(SaplingDbContext db, Dictionary<string, Skill> skills)
    {
        var existing = await db.LearningCourses.Include(c => c.Checkpoints).ToDictionaryAsync(c => c.ExternalId);
        foreach (var source in LearningCourses)
        {
            if (!existing.TryGetValue(source.Id, out var course))
            {
                course = new LearningCourse { ExternalId = source.Id };
                db.LearningCourses.Add(course);
                existing[source.Id] = course;
            }

            course.Provider = source.Provider;
            course.Title = source.Title;
            course.Byline = source.Byline;
            course.Url = source.Url;
            course.Lessons = source.Lessons;
            course.Minutes = source.Minutes;

            for (var i = 0; i < source.Checkpoints.Length; i++)
            {
                var checkpoint = course.Checkpoints.FirstOrDefault(c => c.Order == i);
                if (checkpoint is null)
                {
                    checkpoint = new CourseCheckpoint { Order = i };
                    course.Checkpoints.Add(checkpoint);
                }

                checkpoint.Title = source.Checkpoints[i].Title;
                checkpoint.Lessons = source.Checkpoints[i].Lessons;
                checkpoint.Minutes = source.Checkpoints[i].Minutes;
            }

            db.CourseCheckpoints.RemoveRange(course.Checkpoints.Where(c => c.Order >= source.Checkpoints.Length));
        }

        var kept = LearningCourses.Select(c => c.Id).ToHashSet();
        db.LearningCourses.RemoveRange(existing.Values.Where(c => !kept.Contains(c.ExternalId)));
        await db.SaveChangesAsync();

        await db.SkillCourses.ExecuteDeleteAsync();
        db.SkillCourses.AddRange(SkillCourses
            .Where(p => skills.ContainsKey(p.Key))
            .SelectMany(p => p.Value
                .Where(c => existing.ContainsKey(c.Course))
                .Select(c => new SkillCourse
                {
                    SkillId = skills[p.Key].Id,
                    LearningCourseId = existing[c.Course].Id,
                    Match = c.Match,
                })));
        await db.SaveChangesAsync();
    }

    /// <summary>The course's primary role, falling back to any core role for it, then to Software Developer.</summary>
    public CatalogueRole DefaultRoleFor(string? storedBranch)
    {
        var (course, branch) = CourseCatalog.Parse(storedBranch);
        var matches = Roles
            .Select(r => (Role: r, Relevance: RelevanceFor(r, course, branch)))
            .Where(m => m.Relevance is Primary or Core)
            .ToList();

        return matches.FirstOrDefault(m => m.Relevance == Primary).Role
               ?? matches.FirstOrDefault().Role
               ?? Roles.First(r => r.Onet == "15-1252.00");
    }

    /// <summary>Primary, Core, Adjacent or null. A branch-specific link beats a whole-course ("*") link.</summary>
    public static string? RelevanceFor(CatalogueRole role, string course, string branch) =>
        Links(role)
            .Where(l => string.Equals(l.Course, course, StringComparison.OrdinalIgnoreCase)
                        && (l.Branch == "*" || string.Equals(l.Branch, branch, StringComparison.OrdinalIgnoreCase)))
            .OrderBy(l => l.Branch == "*")
            .ThenBy(l => Rank(l.Relevance))
            .Select(l => l.Relevance)
            .FirstOrDefault();

    public static int Rank(string? relevance) => relevance switch
    {
        Primary => 0,
        Core => 1,
        Adjacent => 2,
        _ => 3,
    };

    private static IEnumerable<(string Course, string Branch, string Relevance)> Links(CatalogueRole role)
    {
        var primary = role.Primary.ToHashSet();
        return role.Core.Select(k => (Key: k, Relevance: primary.Contains(k) ? Primary : Core))
            .Concat(role.Primary.Where(k => !role.Core.Contains(k)).Select(k => (Key: k, Relevance: Primary)))
            .Concat(role.Adjacent.Select(k => (Key: k, Relevance: Adjacent)))
            .Select(x =>
            {
                var parts = x.Key.Split('/', 2);
                return (parts[0], parts.Length > 1 ? parts[1] : "*", x.Relevance);
            });
    }

    private static string Join(IEnumerable<string> values) => string.Join('|', values);
}
